### ISSUE TITLE
执行合约eventContext.getLedger().dataAccount(ASSET_ADDRESS).set(KEY_TOTAL,amount,-1) 报空指针

### ISSUE THREAD

**Issue by dengjinhmm** [blockchain-jd-com/jdchain#12]
java.lang.NullPointerException
	at com.jd.blockchain.ledger.core.DataAccount.setBytes(DataAccount.java:45)
	at com.jd.blockchain.ledger.core.impl.handles.DataAccountKVSetOperationHandle.process(DataAccountKVSetOperationHandle.java:28)
	at com.jd.blockchain.ledger.core.impl.TransactionBatchProcessor$1.handle(TransactionBatchProcessor.java:99)
	at com.jd.blockchain.ledger.core.impl.handles.ContractLedgerContext$DataAccountKVSetOperationExecBuilder.set(ContractLedgerContext.java:294)
	at com.jd.blockchain.contract.OneContractImpl.issue(OneContractImpl.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
	at com.jd.blockchain.contract.jvm.JavaContractCode$ContractThread.run(JavaContractCode.java:73)
	at com.jd.blockchain.runtime.AbstractModule.execute(AbstractModule.java:39)
	at com.jd.blockchain.contract.jvm.JavaContractCode.processEvent(JavaContractCode.java:51)
	at com.jd.blockchain.ledger.core.impl.handles.ContractEventSendOperationHandle.process(ContractEventSendOperationHandle.java:43)
	at com.jd.blockchain.ledger.core.impl.TransactionBatchProcessor.schedule(TransactionBatchProcessor.java:105)
	at com.jd.blockchain.peer.consensus.ConsensusMessageDispatcher$RealmProcessor.schedule(ConsensusMessageDispatcher.java:197)
	at com.jd.blockchain.peer.consensus.ConsensusMessageDispatcher.processOrdered(ConsensusMessageDispatcher.java:76)
	at com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer.blockAndReply(BftsmartNodeServer.java:239)
	at com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer.appExecuteBatch(BftsmartNodeServer.java:228)
	at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:96)
	at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:76)
	at bftsmart.tom.ServiceReplica.receiveMessages(ServiceReplica.java:575)
	at bftsmart.tom.core.DeliveryThread.deliverMessages(DeliveryThread.java:293)
	at bftsmart.tom.core.DeliveryThread.run(DeliveryThread.java:224)

**Comment by dengjinhmm** [comment]
其中参数打印都有值：
assetHolderAddress:5SmMaRLrDht2xjksWHvmovPJYZNrozXtEAPv
amount:5000
ASSET_ADDRESS:5SmEFyCJQGAiQdVJFogKjpbe81CovqCK9u13
KEY_TOTAL:HTMJ_TOTAL

**Comment by dengjinhmm** [comment]
邮箱咨询后问题确定是合约中资产管理账号使用的是用户地址 而不是用数据账户
