### ISSUE TITLE
v1.0.0版本升级后CryptoKeyType doesn't support enum code[-67]!

### ISSUE THREAD

**Issue by dengjin001** [blockchain-jd-com/jdchain#21]
升级1.0.0 后 BlockchainKeyPair类将后面的大写'P'改成了小写，我使用 KeyGenCommand.readxxxKey 报CryptoKeyType doesn't support enum code[-67]!

**Comment by zhaoGuangwei** [comment]
我还没有外露JDChain1.0.0，你已经得到这个版本了？

**Comment by zhaoGuangwei** [comment]
使用新的1.0.0版本后，公私钥生成的格式发生了微调。需要重新生成公私钥，你重新生成一下再试试。如果还有问题，直接微信我。愉快

**Comment by dengjin001** [comment]
BlockchainKeyGenerator.getInstance().generate() 现在无法生成公私钥，Crypto.getAlgorithm 方法中names为null。
 `java.lang.NullPointerException: null
	at com.jd.blockchain.crypto.CryptoAlgorithm.isSignatureAlgorithm(CryptoAlgorithm.java:160)
	at com.jd.blockchain.crypto.Crypto.getSignatureFunction(Crypto.java:280)
	at com.jd.blockchain.ledger.BlockchainKeyGenerator.generate(BlockchainKeyGenerator.java:35)
	at com.jd.blockchain.ledger.BlockchainKeyGenerator.generate(BlockchainKeyGenerator.java:31)
	at com.jd.blockchain.ledger.BlockchainKeyGenerator.generate(BlockchainKeyGenerator.java:26)`

**Comment by dengjin001** [comment]
Crypto类运行静态方法loadDefaultProviders时，pm.getAllProviders 返回提供者服务是空
![image](https://user-images.githubusercontent.com/29300542/60405433-c023da00-9be2-11e9-81fc-5f4231d34326.png)

**Comment by huanghaiquan** [comment]
需要在您的项目中引入一个或者多个具体密码算法库的依赖，例如：
	<dependency>
		<groupId>com.jd.blockchain</groupId>
		<artifactId>crypto-classic</artifactId>
		<version>1.0.0.RELEASE</version>
	</dependency>
	<dependency>
		<groupId>com.jd.blockchain</groupId>
		<artifactId>crypto-sm</artifactId>
		<version>1.0.0.RELEASE</version>
	</dependency>
