### ISSUE TITLE
JD Chain SDK Samples

### ISSUE THREAD

**Issue by ilaotan** [blockchain-jd-com/jdchain#70]
BlockchainKeypair newDataAccount = BlockchainKeyGenerator.getInstance().generate()
这句报
`Exception in thread "main" java.lang.NullPointerException
	at com.jd.blockchain.crypto.CryptoAlgorithm.isSignatureAlgorithm(CryptoAlgorithm.java:160)
	at com.jd.blockchain.crypto.Crypto.getSignatureFunction(Crypto.java:280)
	at com.jd.blockchain.ledger.BlockchainKeyGenerator.generate(BlockchainKeyGenerator.java:35)
	at com.jd.blockchain.ledger.BlockchainKeyGenerator.generate(BlockchainKeyGenerator.java:31)
	at com.jd.blockchain.ledger.BlockchainKeyGenerator.generate(BlockchainKeyGenerator.java:26)
	at com.jd.blockchain.sdk.samples.SDK_InsertData_Demo.insertData(SDK_InsertData_Demo.java:24)
	at com.jd.blockchain.sdk.samples.SDK_InsertData_Demo.main(SDK_InsertData_Demo.java:11)

Process finished with exit code 1
`

请问该如何跑通demo？官方文档感觉太匮乏了

**Comment by imuge** [comment]
@ilaotan 1.4.0我们梳理了下示例代码，可下载编译[JD Chain 1.4.0](https://github.com/blockchain-jd-com/jdchain/tree/release/1.4.0)，参照[samples](https://github.com/blockchain-jd-com/jdchain/tree/release/1.4.0/samples) ，里面提供了可直接运行的环境和测试用例。
