### ISSUE TITLE
1.4.2 无法获得账本

### ISSUE THREAD

**Issue by 18005920002** [blockchain-jd-com/jdchain#73]
步骤：已经成功生成peerX/config/config/ledger-binding.conf,  分别启动peer，查看日志：
`[2021-04-07 16:56:41:054] [main] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Initializing ProtocolHandler ["http-nio-0.0.0.0-7082"]
[2021-04-07 16:56:41:055] [main] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Starting service [Tomcat]
[2021-04-07 16:56:41:055] [main] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Starting Servlet engine: [Apache Tomcat/9.0.31]
[2021-04-07 16:56:41:196] [main] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Initializing Spring embedded WebApplicationContext
[2021-04-07 16:56:41:480] [main] [INFO] - org.reflections.Reflections.scan(Reflections.java:229) - Reflections took 48 ms to scan 5 urls, producing 16 keys and 49 values 
[2021-04-07 16:56:42:104] [main] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Starting ProtocolHandler ["http-nio-0.0.0.0-7082"]
[2021-04-07 16:56:45:009] [scheduling-1] [WARN] - com.jd.blockchain.peer.web.LedgerLoadTimer.ledgerLoad(LedgerLoadTimer.java:89) - Can not load any ledgerBindingConfigs !!!
[2021-04-07 16:56:50:001] [scheduling-1] [WARN] - com.jd.blockchain.peer.web.LedgerLoadTimer.ledgerLoad(LedgerLoadTimer.java:89) - Can not load any ledgerBindingConfigs !!!
[2021-04-07 16:56:55:001] [scheduling-1] [WARN] - com.jd.blockchain.peer.web.LedgerLoadTimer.ledgerLoad(LedgerLoadTimer.java:89) - Can not load any ledgerBindingConfigs !!!
[2021-04-07 16:57:00:013] [scheduling-1] [WARN] - com.jd.blockchain.peer.web.LedgerLoadTimer.ledgerLoad(LedgerLoadTimer.java:89) - Can not load any ledgerBindingConfigs !!!
[2021-04-07 16:57:05:001] [scheduling-1] [WARN] - com.jd.blockchain.peer.web.LedgerLoadTimer.ledgerLoad(LedgerLoadTimer.java:89) - Can not load any ledgerBindingConfigs !!!
`
配置gateway，报告无法连接peer：
`
Start connecting to peer ....
Peer[127.0.0.1:7080] is connected success!
Exception in thread "gateway-ledger-loader-0" java.lang.IllegalArgumentException: Peer addresses must be init first !!!
        at com.jd.blockchain.gateway.service.PeerConnectionManager.monitorAndReconnect(PeerConnectionManager.java:172)
        at com.jd.blockchain.gateway.web.GatewayLedgerLoadTimer.lambda$ledgerLoad$0(GatewayLedgerLoadTimer.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "gateway-ledger-loader-1" java.lang.IllegalArgumentException: Peer addresses must be init first !!!
        at com.jd.blockchain.gateway.service.PeerConnectionManager.monitorAndReconnect(PeerConnectionManager.java:172)
        at com.jd.blockchain.gateway.web.GatewayLedgerLoadTimer.lambda$ledgerLoad$0(GatewayLedgerLoadTimer.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

ledger.init 配置，所有peer的role都是用default。

请问是什么原因？

**Comment by wxiaofan** [comment]
数据库清空一下
