### ISSUE TITLE
com.jd.binaryproto.DataContractException

### ISSUE THREAD

**Issue by SunHao1234** [blockchain-jd-com/jdchain#77]
when I use sdk-samples  for registerUser :

Caused by: com.jd.httpservice.HttpServiceException: No data contract was registered with code[2065851762] and version[8245934934074270309]!
	at com.jd.httpservice.agent.HttpServiceAgent.invoke(HttpServiceAgent.java:580)
	at com.jd.httpservice.agent.HttpServiceAgent.access$000(HttpServiceAgent.java:64)
	at com.jd.httpservice.agent.HttpServiceAgent$ServiceInvocationHandler.invoke(HttpServiceAgent.java:919)
	at com.sun.proxy.$Proxy19.process(Unknown Source)
	at com.jd.blockchain.sdk.client.GatewayServiceFactory$EndpointAutoSigner.process(GatewayServiceFactory.java:209)
	at com.jd.blockchain.transaction.PreparedTx.commit(PreparedTx.java:58)
	at com.jd.blockchain.transaction.StatefulPreparedTx.commit(StatefulPreparedTx.java:57)
	... 23 more

**Comment by imuge** [comment]
看下网关和peer日志，是否有详细的错误记录 @SunHao1234

**Comment by imuge** [comment]
网关侧交易验证失败等异常情况导致抛出异常信息，全局异常管理返回的数据类型与交易提交接口不一致导致sdk端无法解析
