### ISSUE TITLE
网关启动报错 No ledger available from 127.0.0.1:7080

### ISSUE THREAD

**Issue by zenmin** [blockchain-jd-com/jdchain#78]
账本初始化完成，节点状态为已加载，127.0.0.1:7080是可以访问的状态。
修改网关的配置如下：

`#网关的HTTP服务地址；
http.host=0.0.0.0
#网关的HTTP服务端口；
http.port=8080
#网关的HTTP服务上下文路径，可选；
#http.context-path=

#共识节点的服务地址（与该网关节点连接的Peer节点的IP地址）；
peer.host=127.0.0.1
#共识节点的服务端口（与该网关节点连接的Peer节点的端口，即在Peer节点的peer-startup.sh中定义的端口）；
peer.port=7080
#共识节点的服务是否启用安全证书；
peer.secure=false

#账本节点拓扑信息落盘，默认false
topology.store=false

#共识节点的服务提供解析器
#BftSmart共识Provider：com.jd.blockchain.consensus.bftsmart.BftsmartConsensusProvider
#简单消息共识Provider：com.jd.blockchain.consensus.mq.MsgQueueConsensusProvider
peer.providers=com.jd.blockchain.consensus.bftsmart.BftsmartConsensusProvider

#数据检索服务对应URL，格式：http://{ip}:{port}，例如：http://127.0.0.1:10001
#若该值不配置或配置不正确，则浏览器模糊查询部分无法正常显示
data.retrieval.url=
schema.retrieval.url=

#默认公钥的内容（Base58编码数据）；
keys.default.pubkey=7VeRFyhnWVHpCUFLpcXARbnDvMH8mFkHjawwbVfKL9UYNJR2
#默认私钥的路径；在 pk-path 和 pk 之间必须设置其一；
keys.default.privkey-path=
#默认私钥的内容（加密的Base58编码数据）；在 pk-path 和 pk 之间必须设置其一；
keys.default.privkey=177gk1GmT4q1PZJy2Mn9vsHiNnH1uNTuPMVUZZQqGzA88MAMUqCs8stYX5bhawLQhLrMuWK
#默认私钥的解码密码；
keys.default.privkey-password=8EjkXVSTxMFjCvNNsTo8RBMDEVQmk7gYkW4SCDuvdsBG`

启动网关节点报错如下：
`[2021-08-11 09:59:18:525] [main] [ERROR] - com.jd.blockchain.gateway.service.LedgersManager.init(LedgersManager.java:154) - No ledger available from 127.0.0.1:7080
[2021-08-11 09:59:20:121] [main] [ERROR] - com.jd.blockchain.gateway.service.LedgersManager.getLedgers(LedgersManager.java:227) - Get ledgers from 127.0.0.1:7080 error
java.lang.IllegalStateException: No ledger accessible!
        at com.jd.blockchain.sdk.service.PeerBlockchainServiceFactory.create(PeerBlockchainServiceFactory.java:127) ~[sdk-base-1.5.0.RELEASE.jar!/:1.5.0.RELEASE]
        at com.jd.blockchain.sdk.service.PeerBlockchainServiceFactory.connect(PeerBlockchainServiceFactory.java:146) ~[sdk-base-1.5.0.RELEASE.jar!/:1.5.0.RELEASE]
        at com.jd.blockchain.gateway.service.LedgersManager.getLedgers(LedgersManager.java:224) [gateway-1.5.0.RELEASE.jar!/:1.5.0.RELEASE]
        at com.jd.blockchain.gateway.service.LedgersManager.init(LedgersManager.java:147) [gateway-1.5.0.RELEASE.jar!/:1.5.0.RELEASE]
        at com.jd.blockchain.gateway.service.LedgersManager.init(LedgersManager.java:66) [gateway-1.5.0.RELEASE.jar!/:1.5.0.RELEASE]
        at com.jd.blockchain.gateway.GatewayServerBooter.start(GatewayServerBooter.java:181) [gateway-1.5.0.RELEASE.jar!/:1.5.0.RELEASE]
        at com.jd.blockchain.gateway.GatewayServerBooter.main(GatewayServerBooter.java:133) [gateway-1.5.0.RELEASE.jar!/:1.5.0.RELEASE]
        at com.jd.blockchain.gateway.boot.GatewayBooter.main(GatewayBooter.java:19) [classes!/:1.5.0.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [deploy-gateway-1.5.0.RELEASE.jar:1.5.0.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [deploy-gateway-1.5.0.RELEASE.jar:1.5.0.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [deploy-gateway-1.5.0.RELEASE.jar:1.5.0.RELEASE]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [deploy-gateway-1.5.0.RELEASE.jar:1.5.0.RELEASE]`

**tail -f bin/gw.out:** 
![image](https://user-images.githubusercontent.com/28852101/128960231-3bddf5bc-f38a-48f2-9ab3-ea843c5f3e56.png)

版本1.5.0

**Comment by imuge** [comment]
查看下peer进程是否都正常启动，查看下peer/bin/peer.out和peer/logs/peer.error.log是否有错误打印 @zenmin

**Comment by zenmin** [comment]
重新部署又可以正常启动网关了，但是启动之后使用cli执行setkv 注册用户等命令都提示失败  网关日志报错Connection reset by peer，请问是什么原因呢
![image](https://user-images.githubusercontent.com/28852101/129125999-80927a0b-6cb0-48b2-9425-e3eadcc81221.png)
![image](https://user-images.githubusercontent.com/28852101/129126004-2545f92f-7288-499d-bb86-8bc9259beb53.png)

**Comment by zenmin** [comment]
7080peer进程正常
![image](https://user-images.githubusercontent.com/28852101/129126113-5e0c85f1-cc8c-45a9-9b25-8f59dff42e4f.png)

1.5.0和1.4.2都是这样 @imuge

**Comment by zenmin** [comment]
无报错 重新部署又好了
