### ISSUE TITLE
【环境初始化】There is no transaction in the current block, and no empty blocks is allowed!

### ISSUE THREAD

**Issue by jimmy-chow** [blockchain-jd-com/jdchain#80]
版本：1.4.2（1.5.0同样有此问题）

执行./ledger-init.sh，进行账本初始化之后peer0报错

All participants permitted!
------ [[ parallel-dbwrite=false ]] ------
------ [[ max-parallel-dbwrite-size=500 ]] ------
16:45:20.643 ERROR com.jd.blockchain.ledger.core.TransactionBatchProcessor 363 discard - Discard transaction request! --[BlockHeight=0][RequestHash=j5uB5Gh8HWW78CnDintTvXWsFaRsDAV94z1Qapf4mAWAQp][ResponseState=LEDGER_ERROR]
16:45:20.643 ERROR com.jd.blockchain.ledger.core.TransactionBatchProcessor 157 schedule - Ignore transaction caused by LedgerException! --[BlockHeight=0][TxHash=j5uB5Gh8HWW78CnDintTvXWsFaRsDAV94z1Qapf4mAWAQp] --Participant already exist! --[id=LdeNx5SzH6YEuqepbTdwnyVvqSqj7foUDUhU5] com.jd.blockchain.ledger.LedgerException: Participant already exist! --[id=LdeNx5SzH6YEuqepbTdwnyVvqSqj7foUDUhU5]
        at com.jd.blockchain.ledger.core.ParticipantDataset.addConsensusParticipant(ParticipantDataset.java:79) ~[ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.ledger.core.LedgerAdminDataSetEditor.<init>(LedgerAdminDataSetEditor.java:156) ~[ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.ledger.core.LedgerRepositoryImpl.newDataSet(LedgerRepositoryImpl.java:518) ~[ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.ledger.core.LedgerTransactionalEditor.createDatasetFromLastestSnapshot(LedgerTransactionalEditor.java:357) ~[ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.ledger.core.LedgerTransactionalEditor.innerGetDataset(LedgerTransactionalEditor.java:225) ~[ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.ledger.core.LedgerTransactionalEditor.newTransaction(LedgerTransactionalEditor.java:286) ~[ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.ledger.core.TransactionBatchProcessor.schedule(TransactionBatchProcessor.java:127) [ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.ledger.core.LedgerInitializer.prepareLedger(LedgerInitializer.java:218) [ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.ledger.core.LedgerInitializer.prepareLedger(LedgerInitializer.java:168) [ledger-database-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.tools.initializer.web.LedgerInitializeWebController.makeLocalDecision(LedgerInitializeWebController.java:205) [tools-initializer-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.tools.initializer.web.LedgerInitializeWebController.initialize(LedgerInitializeWebController.java:183) [tools-initializer-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.tools.initializer.web.LedgerInitializeWebController.initialize(LedgerInitializeWebController.java:136) [tools-initializer-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.tools.initializer.LedgerInitCommand.startInit(LedgerInitCommand.java:248) [tools-initializer-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.tools.initializer.LedgerInitCommand.main(LedgerInitCommand.java:141) [tools-initializer-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.jd.blockchain.tools.initializer.boot.LedgerInitCommandBooter.main(LedgerInitCommandBooter.java:19) [tools-initializer-booter-1.4.2.RELEASE.jar:1.4.2.RELEASE]

------ Web listener[127.0.0.1:22000] was closed. ------

Error!! -- There is no transaction in the current block, and no empty blocks is allowed!

**Comment by jimmy-chow** [comment]
缺少tools.jar

把\jdk1.8\lib\tools.jar包copy到如下目录里，重启4个节点的manager进程，问题解决。
/home/jdchain/peer0/libs
/home/jdchain/peer1/libs
/home/jdchain/peer2/libs
/home/jdchain/peer3/libs
