### ISSUE TITLE
执行./ledger-init.sh 失败 Error creating bean with name 'ledgerInitializeWebController'

### ISSUE THREAD

**Issue by tang226** [blockchain-jd-com/jdchain#90]
[10:05:00:426] [INFO] - org.springframework.boot.StartupInfoLogger.logStarting(StartupInfoLogger.java:55) - Starting LedgerInitCommand v1.6.2.RELEASE on TH-2209.local with PID 45894 (/Users/bubbleblue/support/2022/2201/86175-0122-1500/jdchain/nodes/peer0/libs/tools-initializer-1.6.2.RELEASE.jar started by bubbleblue in /Users/bubbleblue/support/2022/2201/86175-0122-1500/jdchain/nodes/peer0/bin)
[10:05:00:432] [DEBUG] - org.springframework.boot.StartupInfoLogger.logStarting(StartupInfoLogger.java:56) - Running with Spring Boot v2.2.5.RELEASE, Spring v5.2.4.RELEASE
[10:05:00:433] [INFO] - org.springframework.boot.SpringApplication.logStartupProfileInfo(SpringApplication.java:651) - No active profile set, falling back to default profiles: default
[10:05:01:061] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Initializing ProtocolHandler ["http-nio-127.0.0.1-8800"]
[10:05:01:061] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Starting service [Tomcat]
[10:05:01:061] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Starting Servlet engine: [Apache Tomcat/9.0.31]
[10:05:01:102] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Initializing Spring embedded WebApplicationContext
[10:05:01:206] [DEBUG] - org.reflections.Reflections.scan(Reflections.java:186) - going to scan these urls:
jar:file:/Users/bubbleblue/support/2022/2201/86175-0122-1500/jdchain/nodes/peer0/system/storage-redis-1.6.2.RELEASE.jar!/
jar:file:/Users/bubbleblue/support/2022/2201/86175-0122-1500/jdchain/nodes/peer0/system/storage-composite-1.6.2.RELEASE.jar!/
jar:file:/Users/bubbleblue/support/2022/2201/86175-0122-1500/jdchain/nodes/peer0/system/storage-kvdb-1.6.2.RELEASE.jar!/
jar:file:/Users/bubbleblue/support/2022/2201/86175-0122-1500/jdchain/nodes/peer0/libs/storage-service-1.6.2.RELEASE.jar!/
jar:file:/Users/bubbleblue/support/2022/2201/86175-0122-1500/jdchain/nodes/peer0/system/storage-rocksdb-1.6.2.RELEASE.jar!/
[10:05:01:227] [INFO] - org.reflections.Reflections.scan(Reflections.java:229) - Reflections took 19 ms to scan 5 urls, producing 16 keys and 50 values 
[10:05:01:308] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Stopping service [Tomcat]
[10:05:01:315] [ERROR] - org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:826) - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ledgerInitializeWebController': Unsatisfied dependency expressed through field 'dbConnFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compositeConnectionFactory' defined in class path resource [com/jd/blockchain/storage/service/impl/composite/CompositeStorageConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.jd.blockchain.storage.service.DbConnectionFactory]: Factory method 'compositeConnectionFactory' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib: dlopen(/private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib, 0x0001): tried: '/private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni8593384683284560856.jnilib' (no such file)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.jd.blockchain.tools.initializer.LedgerInitCommand.startInit(LedgerInitCommand.java:363) [tools-initializer-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at com.jd.blockchain.tools.initializer.LedgerInitCommand.main(LedgerInitCommand.java:145) [tools-initializer-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at com.jd.blockchain.tools.initializer.boot.LedgerInitCommandBooter.main(LedgerInitCommandBooter.java:19) [tools-initializer-booter-1.6.2.RELEASE.jar:1.6.2.RELEASE]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compositeConnectionFactory' defined in class path resource [com/jd/blockchain/storage/service/impl/composite/CompositeStorageConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.jd.blockchain.storage.service.DbConnectionFactory]: Factory method 'compositeConnectionFactory' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib: dlopen(/private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib, 0x0001): tried: '/private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni8593384683284560856.jnilib' (no such file)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 19 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.jd.blockchain.storage.service.DbConnectionFactory]: Factory method 'compositeConnectionFactory' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib: dlopen(/private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib, 0x0001): tried: '/private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni8593384683284560856.jnilib' (no such file)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 19 more
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib: dlopen(/private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib, 0x0001): tried: '/private/var/folders/lz/wxxb_kkn1xv0h2jn3rb53mzh0000gn/T/librocksdbjni8593384683284560856.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni8593384683284560856.jnilib' (no such file)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_292]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950) ~[?:1.8.0_292]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832) ~[?:1.8.0_292]
	at java.lang.Runtime.load0(Runtime.java:811) ~[?:1.8.0_292]
	at java.lang.System.load(System.java:1088) ~[?:1.8.0_292]
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79) ~[rocksdbjni-6.3.6.jar:?]
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57) ~[rocksdbjni-6.3.6.jar:?]
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:63) ~[rocksdbjni-6.3.6.jar:?]
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:34) ~[rocksdbjni-6.3.6.jar:?]
	at com.jd.blockchain.storage.service.impl.rocksdb.RocksDBConnectionFactory.<clinit>(RocksDBConnectionFactory.java:23) ~[storage-rocksdb-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_292]
	at com.jd.blockchain.storage.service.impl.composite.CompositeConnectionFactory.init(CompositeConnectionFactory.java:38) ~[storage-composite-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at com.jd.blockchain.storage.service.impl.composite.CompositeConnectionFactory.<init>(CompositeConnectionFactory.java:22) ~[storage-composite-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at com.jd.blockchain.storage.service.impl.composite.CompositeStorageConfiguration.compositeConnectionFactory(CompositeStorageConfiguration.java:19) ~[storage-composite-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at com.jd.blockchain.storage.service.impl.composite.CompositeStorageConfiguration$$EnhancerBySpringCGLIB$$39bec5c2.CGLIB$compositeConnectionFactory$0(<generated>) ~[storage-composite-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at com.jd.blockchain.storage.service.impl.composite.CompositeStorageConfiguration$$EnhancerBySpringCGLIB$$39bec5c2$$FastClassBySpringCGLIB$$2626f697.invoke(<generated>) ~[storage-composite-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at com.jd.blockchain.storage.service.impl.composite.CompositeStorageConfiguration$$EnhancerBySpringCGLIB$$39bec5c2.compositeConnectionFactory(<generated>) ~[storage-composite-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 19 more

**Comment by imuge** [comment]
什么系统环境，jdk版本？ @tang226
